# pyproject.toml
[project]
name = "Rikannodes" # Unique identifier for your node. Immutable after creation.
description = "kijai ComfyUI-PromptRelay with fps and max frame output, multi lora gates, base64 image upload, tiled i2v painter"
version = "1.0.9" # Custom Node version. Must be semantically versioned.
license = { file = "LICENSE.txt" }
dependencies  = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/rikanrino/Rikannodes/"

[tool.comfy]
PublisherId = "rikanrino" # TODO (fill in Publisher ID from Comfy Registry Website).
DisplayName = "Rikannodes" # Display name for the Custom Node. Can be changed later.
Icon = "https://registry.comfy.org/_next/static/media/nodelogo2.9aec72ab.png" # SVG, PNG, JPG or GIF (MAX. 800x400px)
